### PR TITLE
Add DSL datarate_down/up entity in HA sensors

### PR DESCRIPTION
**Pull request by GaryHuang-ASUS**
Start to add datarate_down/up entity in HA sensors. **Not complete yet!**

### CODE REVIEW

**Comment by GaryHuang-ASUS** [comment]
I am still making modifications!

**Comment by GaryHuang-ASUS** [comment]
Hi Vaskivskyi,

I think this data is different from generic network interface? Therefore, I would like to seek your opinion. Which category do you think this sensor should be added to?

**Comment by GaryHuang-ASUS** [comment]
I've confirmed that I've added dsl sensors in bridge.py, but it shows False when I used logger to print out whether `'dsl' in available_sesors` in router.py. 

Did I miss any steps?

**Comment by Vaskivskyi** [comment]
Yes, DSL will be completely different from the other network interfaces (WAN, LAN and wireless ones - those have just the traffic and speed sensors from AsusData.NETWORK.

Here I would go with two independent static sensors. In the const module `STATIC_SENSORS` you can define sensors like this. This would create separate up and down sensors for DSL with both of them enabled by default. They would look similar to those from the other network interfaces already available in the integration, but still provide their own kind of data. Here are all the needed changes to the `const.py`

```python
# Define DSL constant to be used everywhere for the key_group
DSL = "dsl"

# Add which modes of the integration setup
# will have the DSL sensors - this makes sense only
# for routers. Because AP or AiMesh nodes don't
# connect to the network directly
MODE_ROUTER.extend(
    [
        DSL,  # <- add this
        GWLAN,
        "ovpn_client",
        "ovpn_server",
        PARENTAL_CONTROL,
        PORT_FORWARDING,
        "speedtest",
        VPN,
        "wan",
        "wireguard_client",
        "wireguard_server",
    ]
)

# Later in the STATIC_SENSORS add new sensors
STATIC_SENSORS = {
    # Everything which is already there
    # ----------

    # DSL
    ARSensorDescription(
        key="datarate_up",  # <- this is the key which will populate sensor value
        key_group=DSL,  # <- the group of sensors in which to search for the key
        name="DSL Datarate Up",
        icon="mdi:upload-network-outline",
        state_class=SensorStateClass.MEASUREMENT,
        device_class=SensorDeviceClass.DATA_RATE,
        native_unit_of_measurement=UnitOfDataRate.KILOBITS_PER_SECOND,  # <- those are the units from the router
        suggested_unit_of_measurement=UnitOfDataRate.KILOBITS_PER_SECOND,  # <- those will be shown by HA by default
        suggested_display_precision=0,
        entity_registry_enabled_default=True,  # <- the entities will be enabled by default
    ),
    ARSensorDescription(
        key="datarate_down",
        key_group=DSL,
        name="DSL Datarate Down",
        icon="mdi:download-network-outline",
        state_class=SensorStateClass.MEASUREMENT,
        device_class=SensorDeviceClass.DATA_RATE,
        native_unit_of_measurement=UnitOfDataRate.KILOBITS_PER_SECOND,
        suggested_unit_of_measurement=UnitOfDataRate.KILOBITS_PER_SECOND,
        suggested_display_precision=0,
        entity_registry_enabled_default=True,
    ),

    # ----------
    # everything else
}
```

Your `bridge.py` is already good. I would just change the string `"dsl"` when defining the sensors in the `async_get_available_sensors` to the new constant `DSL` from the const module

Then in HA, we'll get something like this

image

**Comment by Vaskivskyi** [comment]
This PR https://github.com/Vaskivskyi/asusrouter/pull/533 will make sure that non-DSL devices won't get sensors created (because the integration function `_get_sensors_modern` will return no sensors in this case) - so no empty entities when they are not needed

**Comment by GaryHuang-ASUS** [comment]
Hi  Vaskivskyi, Thanks for your response! I'll modify the relevant part, test and commit as soon as possible!

I don't have the model with me right now, so it may be able to test it(DSL model) until Monday. I'll check the entity with `non-DSL model` first.

**Comment by GaryHuang-ASUS** [comment]
@Vaskivskyi , Hi Vaskivskyi, I've checked your suggestions. It can work successfully with the PR [#533](https://github.com/Vaskivskyi/asusrouter/pull/533). The sensor entity will display on the board with DSL device.

image

**Comment by Vaskivskyi** [comment]
👍🏻

**Pull request merged**
